embedding:
  class: HuggingFaceEmbedderSentenceTransformers  
  model: Qwen/Qwen3-Embedding-0.6B
  matryoshka_dim: Null 
  doc_prompt: ''
  query_prompt: ''
  normalize: True
  batch_size: Null
  index_method: save_embeddings_torch
  retrieval_method: exact_knn_from_torch_all_in_mem
  k: 10 
data:
  d_text_csv: data/ir/toy_cities/docs.csv
  q_text_csv: data/ir/toy_cities/queries.csv
  index_path: data/ir/toy_cities/qwen_600M/no_prompts/index.pt #suffix -- shelve: .db, faiss: .index
logging:
  level: DEBUG