agent:
  agent_class: GeneralAgent
  max_pipeline_iterations: 1
  policy: PipelinePolicy
  policy_steps:
  - component: HuggingFaceEmbedderSentenceTransformers
    method: exact_knn_from_torch_all_in_mem
data:
  d_text_csv: data/ir/toy_cities/docs.csv
  q_text_csv: data/ir/toy_cities/queries.csv
  index_path: data/ir/toy_cities/qwen_600M/no_prompts/index.pt #suffix -- shelve: .db, faiss: .index
embedding:
  class: HuggingFaceEmbedderSentenceTransformers  
  model: Qwen/Qwen3-Embedding-0.6B
  matryoshka_dim: Null 
  doc_prompt: ''
  query_prompt: ''
  normalize: True
  inference_batch_size: Null
  index_method: save_embeddings_torch
  retrieval_method: exact_knn_from_torch_all_in_mem
  k: 10
  similarity_batch_size: 1 
logging:
  level: DEBUG
